# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPersonInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower_requisition_id', models.CharField(max_length=50)),
                ('interview_process_name', models.CharField(blank=True, max_length=100)),
                ('posting_title', models.CharField(blank=True, max_length=180)),
                ('interviewer_name', models.CharField(max_length=150)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('interview_owner', models.CharField(blank=True, max_length=150)),
                ('schedule_comments', models.TextField(blank=True)),
                ('assessment_name', models.CharField(blank=True, max_length=180)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_person_interviews', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPipelineCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_applied', models.CharField(blank=True, max_length=180)),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screened', 'Screened'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_entries', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('candidate', 'job_applied')},
            },
        ),
    ]
