# Generated by Codex on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videointerviewschedule",
            name="interview_process_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
