# Generated by Django 6.0.2 on 2026-02-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_management", "0002_candidate_remove_candidateevaluation_candidate_id_and_more"),
        ("applicant_tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoInterviewSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manpower_requisition_id", models.CharField(max_length=50)),
                ("posting_title", models.CharField(blank=True, max_length=180)),
                ("interviewer_name", models.CharField(max_length=150)),
                ("provider", models.CharField(choices=[("google_meet", "Google Meet"), ("microsoft_teams", "Microsoft Teams"), ("zoom", "Zoom")], max_length=30)),
                ("meeting_link", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("interview_owner", models.CharField(blank=True, max_length=150)),
                ("schedule_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="video_interviews", to="candidate_management.candidate")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
