# Generated by Django 6.0.2 on 2026-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_tracking", "0002_videointerviewschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inpersoninterview",
            name="manpower_requisition_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="videointerviewschedule",
            name="manpower_requisition_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
