# Generated by Codex on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicant_tracking", "0002_videointerviewschedule_interview_process_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="videointerviewschedule",
            name="cc_emails",
            field=models.TextField(blank=True),
        ),
    ]
