# Generated by Django 6.0.2 on 2026-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_tracking", "0003_alter_req_id_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="videointerviewschedule",
            name="external_meeting_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="host_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="provider_payload",
            field=models.TextField(blank=True),
        ),
    ]
