# Generated by Django 6.0.2 on 2026-02-27 19:05

from django.db import migrations


def backfill_mpr_ids(apps, schema_editor):
    InPersonInterview = apps.get_model("applicant_tracking", "InPersonInterview")
    VideoInterviewSchedule = apps.get_model("applicant_tracking", "VideoInterviewSchedule")

    for item in InPersonInterview.objects.filter(manpower_requisition_id=""):
        item.manpower_requisition_id = f"MPR{item.id:04d}"
        item.save(update_fields=["manpower_requisition_id"])

    for item in VideoInterviewSchedule.objects.filter(manpower_requisition_id=""):
        item.manpower_requisition_id = f"MPR{item.id:04d}"
        item.save(update_fields=["manpower_requisition_id"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_tracking", "0004_video_interview_external_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_mpr_ids, noop_reverse),
    ]
