# Generated by Django 6.0.2 on 2026-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_tracking", "0005_backfill_mpr_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="videointerviewschedule",
            name="email_delivery_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="email_delivery_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
