# Generated by Django 6.0.2 on 2026-03-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_tracking', '0002_videointerviewschedule_interview_process_name'),
        ('applicant_tracking', '0006_video_interview_email_status'),
    ]

    operations = [
    ]
