# Generated by Django 6.0.2 on 2026-03-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_tracking', '0003_videointerviewschedule_cc_emails'),
        ('applicant_tracking', '0007_merge_20260312_1518'),
    ]

    operations = [
    ]
