# Generated by Codex on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicant_tracking", "0008_merge_20260312_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpersoninterview",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="inpersoninterview",
            name="calendar_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="videointerviewschedule",
            name="calendar_sync_error",
            field=models.TextField(blank=True),
        ),
    ]
