# Generated by Django 6.0.2 on 2026-05-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_tracking', '0009_calendar_event_fields'),
        ('candidate_management', '0016_candidatejobapplication_resume_scoring_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower_requisition_id', models.CharField(blank=True, max_length=50)),
                ('interview_process_name', models.CharField(blank=True, max_length=100)),
                ('posting_title', models.CharField(blank=True, max_length=180)),
                ('interviewer_name', models.CharField(max_length=150)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('login_url', models.CharField(blank=True, max_length=255)),
                ('access_notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('interview_owner', models.CharField(blank=True, max_length=150)),
                ('schedule_comments', models.TextField(blank=True)),
                ('assessment_name', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_interviews', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
