# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=220)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='Open', max_length=40)),
                ('priority', models.CharField(default='Medium', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('send_notification_email', models.BooleanField(default=False)),
                ('repeat_enabled', models.BooleanField(default=False)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
