# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecord",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
