# Generated by Django 6.0.2 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0002_taskrecord_timesheet_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrecord",
            name="proof_file",
            field=models.FileField(blank=True, null=True, upload_to="task_proofs/"),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="proof_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="taskrecord",
            name="proof_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
