# Generated by Django 6.0.2 on 2026-03-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_taskrecord_proof_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='job_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='task_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='TaskTimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('entry_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='task_management.taskrecord')),
            ],
        ),
    ]
