# Generated by Django 6.0.2 on 2026-03-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_teams', '0002_recruitmentteammaster_team_roles'),
        ('task_management', '0005_backfill_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment_teams.recruitmentteammaster'),
        ),
    ]
