# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=120)),
                ('verifier_assigned', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('comments', models.TextField(blank=True)),
                ('verification_summary', models.TextField(blank=True)),
                ('score_status', models.CharField(blank=True, max_length=60)),
                ('discrepancies', models.TextField(blank=True)),
                ('id_proof', models.CharField(blank=True, max_length=255)),
                ('address_proof', models.CharField(blank=True, max_length=255)),
                ('education_certificates', models.CharField(blank=True, max_length=255)),
                ('employment_proof', models.CharField(blank=True, max_length=255)),
                ('reference_contacts', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_records', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
