# Generated by Django 6.0.2 on 2026-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentTeamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('team_lead', models.CharField(max_length=120)),
                ('team_members', models.TextField(help_text='Comma separated users')),
                ('department', models.CharField(max_length=80)),
                ('team_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
