# Generated by Django 6.0.2 on 2026-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentteammaster',
            name='team_roles',
            field=models.TextField(blank=True, help_text='Comma separated roles'),
        ),
    ]
