# Generated by Django 6.0.2 on 2026-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=30)),
                ('candidate_name', models.CharField(max_length=150)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('posting_title', models.CharField(max_length=180)),
                ('interviewed_by', models.CharField(max_length=150)),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cultural_fit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interviewer_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Hired', 'Hired'), ('On-Hold', 'On-Hold'), ('Strong Hire', 'Strong Hire'), ('Shortlist', 'Shortlist'), ('Wait-List', 'Wait-List'), ('Move to Next Round', 'Move to Next Round')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
