# Generated by Django 6.0.2 on 2026-02-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('current_city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('pan', models.CharField(blank=True, max_length=20)),
                ('aadhaar', models.CharField(blank=True, max_length=25)),
                ('social_media_link', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('resume_path', models.CharField(blank=True, max_length=255)),
                ('profile_photo_path', models.CharField(blank=True, max_length=255)),
                ('highest_education_level', models.CharField(blank=True, max_length=120)),
                ('degree_name', models.CharField(blank=True, max_length=120)),
                ('institute_name', models.CharField(blank=True, max_length=150)),
                ('year_of_passing', models.CharField(blank=True, max_length=10)),
                ('percentage_cgpa', models.CharField(blank=True, max_length=20)),
                ('certifications', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=80)),
                ('employment_history', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('applied_position', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(default='Applied', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='candidateevaluation',
            old_name='candidate_id',
            new_name='candidate_code',
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='candidate_management.candidate'),
        ),
    ]
