# Generated by Django 6.0.2 on 2026-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='esic',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pf',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
