# Generated by Django 6.0.2 on 2026-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0003_candidate_candidate_code_candidate_esic_candidate_pf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
