# Generated by Django 6.0.2 on 2026-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0004_alter_candidate_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
