# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_management", "0006_merge_0002_candidatejobapplication_0005_alter_candidate_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateevaluation",
            name="assessment_form_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="assessment_form_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="feedback_form_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateevaluation",
            name="feedback_form_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
