# Generated by Codex on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_management", "0011_candidate_custom_tags_candidatenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateevaluation",
            name="interview_round",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
