# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate_management", "0012_candidateevaluation_interview_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("file_path", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("candidate", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="resume_versions", to="candidate_management.candidate")),
            ],
            options={
                "ordering": ["-version", "-uploaded_at"],
                "unique_together": {("candidate", "version")},
            },
        ),
    ]
