# Generated by Django 6.0.2 on 2026-05-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0017_candidateactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatenote',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='candidate_management.candidateactivity'),
        ),
    ]
