from django.urls import path

# pyrefly: ignore [missing-import]
from .views import (
    app_settings_view,
    assessment_form_builder_view,
    assessment_form_delete_confirm_view,
    assessment_form_fill_view,
    bulk_upload_view,
    bulk_upload_map_view,
    bulk_upload_run_view,
    bulk_upload_template_view,
    company_view,
    company_careers_view,
    company_info_view,
    data_export_payload_view,
    data_export_table_view,
    data_export_view,
    email_templates_view,
    email_template_preview_view,
    feedback_form_view,
    integration_view,
    google_calendar_connect_view,
    google_calendar_oauth_callback_view,
    google_calendar_disconnect_view,
    masters_view,
    masters_form_view,
    members_view,
    permission_management_view,
    notification_open_view,
    role_view,
    subscription_billing_view,
    user_master_view,
    global_audit_logs_view,
    onboarding_audit_logs_view,
    workflow_view,
    task_sla_settings_view,
    assessment_form_wizard_view,
)

app_name = "app_settings"

urlpatterns = [
    path("", app_settings_view, name="index"),
    path("audit-logs/", global_audit_logs_view, name="global_audit_logs"),
    path("onboarding-audit-logs/", onboarding_audit_logs_view, name="onboarding_audit_logs"),
    path("assessment-form/", assessment_form_builder_view, name="assessment_builder"),
    path("assessment-form/<int:form_id>/", assessment_form_builder_view, name="assessment_builder"),
    path("assessment-form/wizard/", assessment_form_wizard_view, name="assessment_wizard"),
    path("assessment-form/wizard/<int:form_id>/", assessment_form_wizard_view, name="assessment_wizard"),
    path("assessment-form/delete/<int:form_id>/", assessment_form_delete_confirm_view, name="assessment_delete_confirm"),
    path("assessment-form/<int:form_id>/fill/", assessment_form_fill_view, name="assessment_fill"),
    path("masters/", masters_view, name="masters"),
    path("masters/<slug:master_key>/", masters_form_view, name="masters_form"),
    path("members/", members_view, name="members"),
    path("email-templates/", email_templates_view, name="email_templates"),
    path("email-templates/preview/", email_template_preview_view, name="email_template_preview"),
    path("feedback-form/", feedback_form_view, name="feedback_form"),
    path("bulk-upload/", bulk_upload_view, name="bulk_upload"),
    path("bulk-upload/template/", bulk_upload_template_view, name="bulk_upload_template"),
    path("bulk-upload/map/", bulk_upload_map_view, name="bulk_upload_map"),
    path("bulk-upload/run/", bulk_upload_run_view, name="bulk_upload_run"),
    path("integration/", integration_view, name="integration"),
    path("integration/google-calendar/connect/", google_calendar_connect_view, name="google_calendar_connect"),
    path("integration/google-calendar/callback/", google_calendar_oauth_callback_view, name="google_calendar_oauth_callback"),
    path("integration/google-calendar/disconnect/", google_calendar_disconnect_view, name="google_calendar_disconnect"),
    path("workflow/", workflow_view, name="workflow"),
    path("data-export/", data_export_view, name="data_export"),
    path("data-export/table/<str:table_name>/", data_export_table_view, name="data_export_table"),
    path("data-export/payload/", data_export_payload_view, name="data_export_payload"),
    path("subscription-billing/", subscription_billing_view, name="subscription_billing"),
    path("company/", company_view, name="company"),
    path("company/info/", company_info_view, name="company_info"),
    path("company/careers/", company_careers_view, name="company_careers"),
    path("role/", role_view, name="role"),
    path("user-master/", user_master_view, name="user_master"),
    path("permission-management/", permission_management_view, name="permission_management"),
    path("task-sla/", task_sla_settings_view, name="task_sla_settings"),
    path("notifications/open/<int:notification_id>/", notification_open_view, name="notification_open"),
]
