# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewers', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('In Person', 'In Person'), ('Video', 'Video')], max_length=20)),
                ('video_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_schedules', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=150)),
                ('video_file_name', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
