# Generated by Django 6.0.2 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview_recording", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewrecording",
            name="dominant_emotion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="emotion_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="emotion_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="emotion_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewrecording",
            name="video_file_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
