# Generated by Django 6.0.2 on 2026-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_recording', '0002_interviewrecording_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecording',
            name='anonymized_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='pii_redacted',
            field=models.BooleanField(default=False),
        ),
    ]
