from copy import deepcopy


DEMO_DATA_VERSION = 5


def _demo_seed():
    return {
        "candidate_list_records": [
            {
                "id": "C0001",
                "name": "Aarav Sharma",
                "email": "aarav.sharma@demo.com",
                "phone": "9876543210",
                "position": "Python Developer",
                "status": "In Progress",
                "status_class": "status-pill inprogress",
                "aadhaar": "4123-1111-2222",
                "pan": "AARAV1234K",
                "pf": "PF1001",
                "esic": "ESIC1001",
                "skills": "Python, Django, REST",
                "experience": "4 Years",
            },
            {
                "id": "C0002",
                "name": "Neha Verma",
                "email": "neha.verma@demo.com",
                "phone": "9988776655",
                "position": "QA Engineer",
                "status": "Under Review",
                "status_class": "status-pill review",
                "aadhaar": "5123-2222-3333",
                "pan": "NEHAV5678Q",
                "pf": "PF1002",
                "esic": "ESIC1002",
                "skills": "Selenium, API Testing",
                "experience": "3 Years",
            },
            {
                "id": "C0003",
                "name": "Rahul Jain",
                "email": "rahul.jain@demo.com",
                "phone": "9123456780",
                "position": ".NET Developer",
                "status": "Technical Interview",
                "status_class": "status-pill interview",
                "aadhaar": "6123-3333-4444",
                "pan": "RAHUL6789L",
                "pf": "PF1003",
                "esic": "ESIC1003",
                "skills": ".NET, C#, SQL",
                "experience": "5 Years",
            },
            {
                "id": "C0004",
                "name": "Priya Nair",
                "email": "priya.nair@demo.com",
                "phone": "9001122334",
                "position": "Business Analyst",
                "status": "Shortlisted",
                "status_class": "status-pill review",
                "aadhaar": "7123-4444-5555",
                "pan": "PRIYA4321M",
                "pf": "PF1004",
                "esic": "ESIC1004",
                "skills": "BA, Requirement Gathering",
                "experience": "4 Years",
            },
        ],
        "candidate_database_rows": [
            {
                "candidate_id": "C0001",
                "name": "Aarav Sharma",
                "email": "aarav.sharma@demo.com",
                "phone": "9876543210",
                "aadhaar": "4123-1111-2222",
                "pan": "AARAV1234K",
                "pf": "PF1001",
                "esic": "ESIC1001",
                "skills": "Python, Django, REST",
                "job_applied": "Python Developer",
                "status": "In Progress",
                "personal_info": "Aarav Sharma | 9876543210 | aarav.sharma@demo.com",
                "experience": "4 Years",
                "bgv_status": "In Progress",
                "interview_scores": "Tech: 8.2 | Comm: 7.8",
            },
            {
                "candidate_id": "C0002",
                "name": "Neha Verma",
                "email": "neha.verma@demo.com",
                "phone": "9988776655",
                "aadhaar": "5123-2222-3333",
                "pan": "NEHAV5678Q",
                "pf": "PF1002",
                "esic": "ESIC1002",
                "skills": "Selenium, API Testing",
                "job_applied": "QA Engineer",
                "status": "Shortlisted",
                "personal_info": "Neha Verma | 9988776655 | neha.verma@demo.com",
                "experience": "3 Years",
                "bgv_status": "Pending",
                "interview_scores": "Tech: 7.5 | Comm: 8.1",
            },
            {
                "candidate_id": "C0004",
                "name": "Priya Nair",
                "email": "priya.nair@demo.com",
                "phone": "9001122334",
                "aadhaar": "7123-4444-5555",
                "pan": "PRIYA4321M",
                "pf": "PF1004",
                "esic": "ESIC1004",
                "skills": "BA, Requirement Gathering",
                "job_applied": "Business Analyst",
                "status": "Shortlisted",
                "personal_info": "Priya Nair | 9001122334 | priya.nair@demo.com",
                "experience": "4 Years",
                "bgv_status": "Pending",
                "interview_scores": "Tech: 7.9 | Comm: 8.4",
            },
        ],
        "job_requisition_dashboard_rows": [
            {
                "job_id": "JOB101",
                "title": "Python Developer",
                "department": "Engineering",
                "openings": 3,
                "applications_received": 24,
                "status": "Open",
            },
            {
                "job_id": "JOB102",
                "title": "QA Engineer",
                "department": "Quality",
                "openings": 2,
                "applications_received": 17,
                "status": "In Review",
            },
        ],
        "job_position_rows": [
            {
                "job_id": "JOB101",
                "job_title": "Python Developer",
                "department": "Engineering",
                "location": "Bangalore",
                "skills_required": "Python, Django, SQL",
                "experience_range": "3-6 Years",
                "job_description": "Backend development and API integration.",
                "hiring_manager": "R. Kulkarni",
                "approval_status": "Approved",
            },
            {
                "job_id": "JOB102",
                "job_title": "QA Engineer",
                "department": "Quality",
                "location": "Pune",
                "skills_required": "Selenium, API Testing",
                "experience_range": "2-5 Years",
                "job_description": "Automation and release validation.",
                "hiring_manager": "N. Menon",
                "approval_status": "Pending",
            },
        ],
        "job_approval_rows": [
            {
                "job_id": "JOB101",
                "submitted_by": "Administrator",
                "approved_by": "HR Manager",
                "approval_status": "Approved",
                "comments": "Hiring budget approved.",
            },
            {
                "job_id": "JOB102",
                "submitted_by": "Recruiter 1",
                "approved_by": "Department Head",
                "approval_status": "In Progress",
                "comments": "Awaiting final sign-off.",
            },
        ],
        "bgv_submission_rows": [
            {
                "candidate_id": "C0001",
                "id_proof": "Aadhaar Uploaded",
                "address_proof": "Utility Bill Uploaded",
                "education_certificates": "Submitted",
                "employment_proof": "Submitted",
                "reference_contacts": "2 Added",
            },
            {
                "candidate_id": "C0002",
                "id_proof": "Passport Uploaded",
                "address_proof": "Bank Statement Uploaded",
                "education_certificates": "Submitted",
                "employment_proof": "Pending",
                "reference_contacts": "1 Added",
            },
        ],
        "bgv_verification_rows": [
            {
                "candidate_id": "C0001",
                "document_type": "Education + Employment",
                "verifier_assigned": "BGV Team A",
                "status": "In Progress",
                "comments": "University verification in progress.",
            },
            {
                "candidate_id": "C0002",
                "document_type": "Address + ID",
                "verifier_assigned": "BGV Team B",
                "status": "Pending",
                "comments": "Awaiting employment proof.",
            },
        ],
        "bgv_report_rows": [
            {
                "candidate_id": "C0001",
                "verification_summary": "All checks passed except employment pending.",
                "score_status": "86 / In Progress",
                "discrepancies": "None",
            },
            {
                "candidate_id": "C0002",
                "verification_summary": "ID and address validated.",
                "score_status": "72 / Pending",
                "discrepancies": "Employment documents missing",
            },
        ],
        "interview_panel_records": [
            {
                "candidate": "Aarav Sharma",
                "interviewers": "Priya Nair, Rohit Singh",
                "date": "2026-02-26",
                "time": "11:00",
                "mode": "Video",
                "video_link": "https://meet.demo.com/aarav",
                "created_at": "2026-02-22 10:30",
            },
            {
                "candidate": "Neha Verma",
                "interviewers": "Ankit Jain",
                "date": "2026-02-27",
                "time": "15:30",
                "mode": "In Person",
                "video_link": "",
                "created_at": "2026-02-22 11:00",
            },
        ],
        "interview_recording_records": [
            {
                "candidate": "Aarav Sharma",
                "interviewer": "Priya Nair",
                "video_file_name": "aarav_round1.mp4",
                "transcript": "Candidate explained API design and async workflows clearly.",
                "sentiment_score": "8.40",
                "created_at": "2026-02-22 17:20",
            },
            {
                "candidate": "Neha Verma",
                "interviewer": "Ankit Jain",
                "video_file_name": "neha_round1.mp4",
                "transcript": "Strong QA fundamentals and good communication.",
                "sentiment_score": "8.10",
                "created_at": "2026-02-22 18:05",
            },
        ],
        "interview_evaluation_records": [
            {
                "candidate_id": "C0001",
                "candidate_name": "Aarav Sharma",
                "interviewer_name": "Priya Nair",
                "technical_score": "8.2",
                "communication_score": "7.8",
                "cultural_fit_score": "8.0",
                "comments": "Good backend depth.",
                "submitted_at": "2026-02-22 17:45",
            },
            {
                "candidate_id": "C0002",
                "candidate_name": "Neha Verma",
                "interviewer_name": "Ankit Jain",
                "technical_score": "7.6",
                "communication_score": "8.3",
                "cultural_fit_score": "7.9",
                "comments": "Strong QA process knowledge.",
                "submitted_at": "2026-02-22 18:15",
            },
        ],
        "candidate_evaluation_records": [
            {
                "candidate_id": "C0001",
                "candidate_name": "Aarav Sharma",
                "candidate_phone": "9876543210",
                "candidate_email": "aarav.sharma@demo.com",
                "posting_title": "Python Developer",
                "interviewed_by": "Priya Nair",
                "technical_score": "8.2",
                "communication_score": "7.8",
                "cultural_fit_score": "8.0",
                "overall_rating": "8.0",
                "interviewer_comments": "Strong in architecture and APIs.",
                "status": "Move to Next Round",
            },
            {
                "candidate_id": "C0002",
                "candidate_name": "Neha Verma",
                "candidate_phone": "9988776655",
                "candidate_email": "neha.verma@demo.com",
                "posting_title": "QA Engineer",
                "interviewed_by": "Ankit Jain",
                "technical_score": "7.6",
                "communication_score": "8.3",
                "cultural_fit_score": "7.9",
                "overall_rating": "7.93",
                "interviewer_comments": "Good test strategy understanding.",
                "status": "Shortlist",
            },
        ],
        "candidate_dashboard_rows": [
            {
                "candidate_id": "C0001",
                "job_applied": "Python Developer",
                "status": "Interview Scheduled",
                "interview_schedule": "2026-02-26 11:00",
                "bgv_status": "In Progress",
                "documents_uploaded": "6/7",
                "offer_letter": "Not Issued",
            },
            {
                "candidate_id": "C0002",
                "job_applied": "QA Engineer",
                "status": "Shortlisted",
                "interview_schedule": "2026-02-27 15:30",
                "bgv_status": "Pending",
                "documents_uploaded": "5/7",
                "offer_letter": "Not Issued",
            },
        ],
        "team_dashboard_rows": [
            {
                "team": "IT Hiring Team",
                "tasks_pending": 9,
                "tasks_completed": 21,
                "total_hours": "146h",
                "productivity_metrics": "82%",
            },
            {
                "team": "Quality Hiring Team",
                "tasks_pending": 6,
                "tasks_completed": 18,
                "total_hours": "128h",
                "productivity_metrics": "79%",
            },
        ],
        "task_records": [
            {
                "owner": "Administrator",
                "subject": "Schedule L2 panel",
                "due_date": "2026-02-26",
                "status": "Open",
                "priority": "High",
                "candidate": "Aarav Sharma",
            },
            {
                "owner": "Recruiter 1",
                "subject": "Collect BGV documents",
                "due_date": "2026-02-28",
                "status": "In Progress",
                "priority": "Medium",
                "candidate": "Neha Verma",
            },
        ],
        "application_pipeline_candidates": [
            {
                "candidate_id": "C0001",
                "name": "Aarav Sharma",
                "job_applied": "Python Developer",
                "stage": "Applied",
                "last_updated": "2026-02-18",
            },
            {
                "candidate_id": "C0002",
                "name": "Neha Verma",
                "job_applied": "QA Engineer",
                "stage": "Screened",
                "last_updated": "2026-02-17",
            },
            {
                "candidate_id": "C0003",
                "name": "Rahul Jain",
                "job_applied": ".NET Developer",
                "stage": "Interview",
                "last_updated": "2026-02-19",
            },
            {
                "candidate_id": "C0004",
                "name": "Priya Nair",
                "job_applied": "Business Analyst",
                "stage": "Offer",
                "last_updated": "2026-02-16",
            },
            {
                "candidate_id": "C0005",
                "name": "Vikram Singh",
                "job_applied": "Data Engineer",
                "stage": "Hired",
                "last_updated": "2026-02-14",
            },
            {
                "candidate_id": "C0006",
                "name": "Isha Patel",
                "job_applied": "Frontend Developer",
                "stage": "Rejected",
                "last_updated": "2026-02-15",
            },
        ],
        "in_person_interview_rows": [
            {
                "manpower_requisition_id": "MR1001",
                "interview_process_name": "Round 1",
                "candidate_name": "Aarav Sharma",
                "posting_title": "Python Developer",
                "interviewer_name": "Priya Nair",
                "client_name": "ABC Corp",
                "date": "2026-02-26",
                "from_time": "11:00",
                "to_time": "12:00",
                "location": "Bangalore Office",
                "interview_owner": "Administrator",
                "schedule_comments": "Bring government ID",
                "assessment_name": "Candidate Technical Assessment",
                "attachment_name": "invite_mr1001.pdf",
                "created_at": "2026-02-22 10:30",
            },
            {
                "manpower_requisition_id": "MR1002",
                "interview_process_name": "Round 2",
                "candidate_name": "Neha Verma",
                "posting_title": "QA Engineer",
                "interviewer_name": "Ankit Jain",
                "client_name": "XYZ Systems",
                "date": "2026-02-27",
                "from_time": "15:30",
                "to_time": "16:30",
                "location": "Pune Office",
                "interview_owner": "Recruiter 1",
                "schedule_comments": "Panel of two interviewers",
                "assessment_name": "HR Final Assessment",
                "attachment_name": "invite_mr1002.pdf",
                "created_at": "2026-02-22 11:15",
            },
        ],
        "settings_master_records": {
            "city": [
                {"name": "Bangalore", "code": "BLR"},
                {"name": "Pune", "code": "PUN"},
            ],
            "state": [
                {"name": "Karnataka", "code": "KA"},
                {"name": "Maharashtra", "code": "MH"},
            ],
            "country": [
                {"name": "India", "code": "IN"},
                {"name": "United Arab Emirates", "code": "AE"},
            ],
            "education-level": [
                {"name": "Bachelor", "code": "UG"},
                {"name": "Master", "code": "PG"},
            ],
        },
        "settings_company_records": [
            {
                "company_name": "Ultimatix Technologies",
                "domain": "ultimatix.demo",
                "website": "https://ultimatix.demo",
                "location": "Bangalore",
                "strength": "500+",
                "industry": "HR Tech",
                "social_link": "https://linkedin.com/company/ultimatix-demo",
            }
        ],
        "settings_role_records": [
            {
                "id": "1",
                "role_id": "ROLE0001",
                "role_name": "Administrator",
                "role_description": "System-wide administration",
                "role_level": "Admin",
                "status": "Active",
                "created_by": "Administrator",
                "created_date": "2026-02-20 10:00",
            },
            {
                "id": "2",
                "role_id": "ROLE0002",
                "role_name": "Recruiter",
                "role_description": "Candidate and requisition handling",
                "role_level": "User",
                "status": "Active",
                "created_by": "Administrator",
                "created_date": "2026-02-20 10:30",
            },
        ],
        "settings_user_records": [
            {
                "id": "1",
                "user_id": "USR0001",
                "first_name": "Aman",
                "last_name": "Sharma",
                "full_name": "Aman Sharma",
                "email_id": "aman.sharma@ultimatix.demo",
                "mobile_number": "9876500001",
                "department": "HR",
                "role": "Administrator",
                "team": "IT Hiring Team",
                "status": "Active",
                "allowed_modules": "ATS,BGV,Interview,Reports,Admin",
                "created_date": "2026-02-20 11:00",
            },
            {
                "id": "2",
                "user_id": "USR0002",
                "first_name": "Neha",
                "last_name": "Verma",
                "full_name": "Neha Verma",
                "email_id": "neha.verma@ultimatix.demo",
                "mobile_number": "9876500002",
                "department": "Operations",
                "role": "Recruiter",
                "team": "QA Hiring Team",
                "status": "Active",
                "allowed_modules": "ATS,Interview,Reports",
                "created_date": "2026-02-20 11:20",
            },
        ],
        "settings_user_audits": {
            "1": [
                {"changed_at": "2026-02-21 09:30", "action": "User Created", "details": "Created with role Administrator.", "changed_by": "Administrator"},
                {"changed_at": "2026-02-22 12:10", "action": "User Updated", "details": "Updated team mapping.", "changed_by": "Administrator"},
            ],
            "2": [
                {"changed_at": "2026-02-21 10:00", "action": "User Created", "details": "Created with role Recruiter.", "changed_by": "Administrator"},
            ],
        },
        "settings_permission_records": [
            {
                "role": "Administrator",
                "module": "ATS",
                "sub_module": "Candidate",
                "create_permission": True,
                "view_permission": True,
                "edit_permission": True,
                "delete_permission": True,
                "approve_permission": True,
                "export_permission": True,
                "download_permission": True,
                "assign_permission": True,
                "full_access": True,
            },
            {
                "role": "Recruiter",
                "module": "Interview",
                "sub_module": "Interview",
                "create_permission": True,
                "view_permission": True,
                "edit_permission": True,
                "delete_permission": False,
                "approve_permission": False,
                "export_permission": True,
                "download_permission": True,
                "assign_permission": True,
                "full_access": False,
            },
        ],
        "settings_assessment_forms": [
            {
                "id": 9001,
                "name": "Technical Round Assessment",
                "description": "Evaluate technical capability and communication.",
                "fields": [
                    {"label": "Candidate ID", "field_name": "candidate_id", "field_type": "text", "required": True, "options": ""},
                    {"label": "Candidate Name", "field_name": "candidate_name", "field_type": "text", "required": True, "options": ""},
                    {"label": "Interviewer", "field_name": "interviewer", "field_type": "text", "required": True, "options": ""},
                    {"label": "Technical Score", "field_name": "technical_score", "field_type": "number", "required": True, "options": ""},
                    {"label": "Communication Score", "field_name": "communication_score", "field_type": "number", "required": True, "options": ""},
                    {"label": "Recommendation", "field_name": "recommendation", "field_type": "select", "required": True, "options": "Strong Hire,Hire,Hold,Reject"},
                    {"label": "Comments", "field_name": "comments", "field_type": "textarea", "required": False, "options": ""},
                ],
            },
            {
                "id": 9002,
                "name": "HR Round Assessment",
                "description": "Evaluate cultural fit, expectation, and policy alignment.",
                "fields": [
                    {"label": "Candidate ID", "field_name": "candidate_id", "field_type": "text", "required": True, "options": ""},
                    {"label": "Candidate Name", "field_name": "candidate_name", "field_type": "text", "required": True, "options": ""},
                    {"label": "Culture Fit Score", "field_name": "culture_fit_score", "field_type": "number", "required": True, "options": ""},
                    {"label": "Notice Period", "field_name": "notice_period", "field_type": "text", "required": False, "options": ""},
                    {"label": "Final HR Status", "field_name": "final_hr_status", "field_type": "select", "required": True, "options": "Shortlist,On Hold,Reject"},
                ],
            },
        ],
        "settings_assessment_entries": {
            "9001": [
                {
                    "candidate_id": "C0001",
                    "candidate_name": "Aarav Sharma",
                    "interviewer": "Priya Nair",
                    "technical_score": "8.2",
                    "communication_score": "7.8",
                    "recommendation": "Hire",
                    "comments": "Strong backend fundamentals.",
                },
                {
                    "candidate_id": "C0002",
                    "candidate_name": "Neha Verma",
                    "interviewer": "Ankit Jain",
                    "technical_score": "7.6",
                    "communication_score": "8.3",
                    "recommendation": "Strong Hire",
                    "comments": "Great QA depth and communication.",
                },
            ],
            "9002": [
                {
                    "candidate_id": "C0001",
                    "candidate_name": "Aarav Sharma",
                    "culture_fit_score": "8.0",
                    "notice_period": "30 Days",
                    "final_hr_status": "Shortlist",
                }
            ],
        },
    }


class DemoUiDataMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        current_version = request.session.get("ui_demo_data_version")
        if current_version != DEMO_DATA_VERSION:
            for key, value in _demo_seed().items():
                request.session[key] = deepcopy(value)
            request.session["ui_demo_data_version"] = DEMO_DATA_VERSION
        response = self.get_response(request)
        return response
