# Generated by Django 6.0.2 on 2026-02-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('skills_required', models.TextField(blank=True)),
                ('experience_range', models.CharField(blank=True, max_length=80)),
                ('job_description', models.TextField(blank=True)),
                ('hiring_manager', models.CharField(blank=True, max_length=150)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('approval_status', models.CharField(default='Pending', max_length=40)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='job_requisition.jobrequisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
