# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_requisition", "0002_jobrequisition_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequisition",
            name="public_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
