# Generated by Django 6.0.2 on 2026-05-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_management', '0016_candidatejobapplication_resume_scoring_details'),
        ('onboarding', '0005_onboardingsigndocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_audit_logs', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSigningCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pdf', models.FileField(upload_to='onboarding/certificates/')),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='onboarding.onboardingsigndocument')),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='onboarding.onboardingsignaturerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
