# Generated by Django 6.0.2 on 2026-05-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0023_alter_googleoauthtoken_id'),
        ('candidate_management', '0016_candidatejobapplication_resume_scoring_details'),
        ('onboarding', '0006_onboardingauditlog_onboardingsigningcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_actions', to='app_settings.usermaster'),
        ),
        migrations.AlterField(
            model_name='onboardingauditlog',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_audit_logs', to='candidate_management.candidate'),
        ),
    ]
