# Generated by Django 6.0.2 on 2026-05-19 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('context', models.CharField(choices=[('assessment', 'Candidate Assessment'), ('evaluation', 'Interview Evaluation')], default='assessment', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Assessment token or evaluation ID', max_length=200)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('candidate_email', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated – Too Many Violations')], default='active', max_length=20)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('max_warnings', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proctoring Session',
                'verbose_name_plural': 'Proctoring Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base64-encoded JPEG snapshot')),
                ('face_count', models.IntegerField(default=-1, help_text='-1 = not analysed, 0 = no face, 1 = ok, 2+ = multiple')),
                ('flagged', models.BooleanField(default=False, help_text='True if face_count is 0 or >1')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'Proctoring Snapshot',
                'verbose_name_plural': 'Proctoring Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch / Window Blur'), ('fullscreen_exit', 'Exited Fullscreen'), ('devtools_open', 'DevTools Opened'), ('copy_paste', 'Copy/Paste Attempt'), ('right_click', 'Right-Click Attempt'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Extra context (e.g. tab URL, window dimensions)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'Violation Log',
                'verbose_name_plural': 'Violation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
