# Generated by Django 6.0.2 on 2026-02-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_management', '0002_candidate_remove_candidateevaluation_candidate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='candidate_management.candidate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
