# Generated by Django 6.0.2 on 2026-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_city_country_educationlevel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('domain', models.CharField(blank=True, max_length=120)),
                ('website', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('social_link', models.CharField(blank=True, max_length=255)),
                ('company_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
