# Generated by Django 6.0.2 on 2026-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('role_name', models.CharField(max_length=120, unique=True)),
                ('role_description', models.TextField(blank=True)),
                ('role_level', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('User', 'User')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_by', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
