# Generated by Django 6.0.2 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_rolemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=80)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('reporting_manager', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('employee_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/profile/')),
                ('allowed_modules', models.TextField(help_text='Comma separated modules')),
                ('ip_restriction_enabled', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
