# Generated by Django 6.0.2 on 2026-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_usermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=80)),
                ('sub_module', models.CharField(max_length=120)),
                ('create_permission', models.BooleanField(default=False)),
                ('view_permission', models.BooleanField(default=False)),
                ('edit_permission', models.BooleanField(default=False)),
                ('delete_permission', models.BooleanField(default=False)),
                ('approve_permission', models.BooleanField(default=False)),
                ('export_permission', models.BooleanField(default=False)),
                ('download_permission', models.BooleanField(default=False)),
                ('assign_permission', models.BooleanField(default=False)),
                ('full_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
