# Generated by Django 6.0.2 on 2026-02-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_rolepermissionsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMasterAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True)),
                ('changed_by', models.CharField(max_length=120)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app_settings.usermaster')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
