# Generated by Django 6.0.2 on 2026-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0007_usermasteraudit"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewIntegrationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_key", models.CharField(max_length=30, unique=True)),
                ("provider_label", models.CharField(max_length=80)),
                ("is_enabled", models.BooleanField(default=False)),
                ("meeting_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider_label"],
            },
        ),
    ]
