# Generated by Django 6.0.2 on 2026-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0008_interviewintegrationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewintegrationsetting",
            name="credential_json",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewintegrationsetting",
            name="organizer_email",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
