# Generated by Django 6.0.2 on 2026-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0009_interviewintegration_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDeliveryConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("smtp_enabled", models.BooleanField(default=False)),
                ("host", models.CharField(blank=True, max_length=150)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                ("from_email", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
