# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0010_emaildeliveryconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentform",
            name="form_type",
            field=models.CharField(
                choices=[("assessment", "Assessment Form"), ("feedback", "Feedback Form")],
                default="assessment",
                max_length=20,
            ),
        ),
    ]
