# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0011_assessmentform_form_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalRoleAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_name", models.CharField(max_length=120)),
                (
                    "module_key",
                    models.CharField(
                        choices=[
                            ("candidate_db", "Candidate DB"),
                            ("job_posting", "Job Posting"),
                            ("interview", "Interview"),
                            ("bgv", "BGV"),
                            ("timesheet", "Timesheet"),
                            ("admin", "Admin"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("no", "No"),
                            ("self_only", "Self only"),
                            ("assigned_only", "Assigned only"),
                            ("view", "View"),
                            ("approve", "Approve"),
                            ("fill", "Fill"),
                            ("feedback", "Feedback"),
                            ("limited", "Limited"),
                            ("read_only", "Read Only"),
                            ("full", "Full"),
                        ],
                        default="no",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role_name", "module_key"],
                "unique_together": {("role_name", "module_key")},
            },
        ),
    ]
