# Generated by Django 6.0.2 on 2026-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0015_seed_role_permission_setup_module_submodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('tel', 'Phone'), ('url', 'URL'), ('time', 'Time'), ('datetime', 'Date & Time'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
    ]
