# Generated by Codex on 2026-03-13

from django.db import migrations, models


def seed_placeholders(apps, schema_editor):
    EmailPlaceholder = apps.get_model("app_settings", "EmailPlaceholder")
    defaults = [
        ("candidate_name", "Candidate Name", "Amit Kumar", "Candidate full name"),
        ("candidate_email", "Candidate Email", "amit@example.com", "Candidate email address"),
        ("interviewer_name", "Interviewer Name", "Neha Verma", "Interviewer full name"),
        ("interview_date", "Interview Date", "2026-03-15", "Scheduled interview date"),
        ("interview_time", "Interview Time", "10:00 - 11:00", "Scheduled interview time"),
        ("job_title", "Job Title", "Senior Developer", "Job posting title"),
        ("meeting_link", "Meeting Link", "https://meet.example.com/abc", "Interview meeting link"),
    ]
    for key, label, example, description in defaults:
        EmailPlaceholder.objects.get_or_create(
            key=key,
            defaults={"label": label, "example": example, "description": description},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0018_emailtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailPlaceholder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("example", models.CharField(blank=True, max_length=180)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["key"]},
        ),
        migrations.RunPython(seed_placeholders, migrations.RunPython.noop),
    ]
