# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0019_emailplaceholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="module",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="trigger",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="to_emails",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="cc_emails",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="bcc_emails",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
