# Generated by Codex on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0020_emailtemplate_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleOAuthToken",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="google_calendar", max_length=40)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_uri", models.CharField(blank=True, max_length=255)),
                ("scopes", models.TextField(blank=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="google_oauth_tokens", to="app_settings.usermaster")),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
