# Generated by Django 6.0.2 on 2026-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0022_company_service_agreement_and_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
