# Generated by Django 6.0.2 on 2026-05-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0023_alter_googleoauthtoken_id'),
        ('candidate_management', '0016_candidatejobapplication_resume_scoring_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('onboarding', 'Onboarding'), ('job_requisition', 'Job Requisition'), ('applicant_tracking', 'Applicant Tracking'), ('assessment', 'Assessment Builder'), ('candidate_management', 'Candidate Management'), ('app_settings', 'Settings'), ('interview', 'Interview Evaluation')], max_length=50)),
                ('action', models.CharField(max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_audit_logs', to='candidate_management.candidate')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_audit_entries', to='app_settings.usermaster')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
